// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Calendar struct {
	ID           string `json:"id" bson:"id"`
	RequestIDRef string `json:"requestIdRef" bson:"requestIdRef"`
	CalendarType string `json:"calendarType" bson:"calendarType"`
	DateTimeFrom string `json:"dateTimeFrom" bson:"dateTimeFrom"`
	DateTimeTo   string `json:"dateTimeTo" bson:"dateTimeTo"`
	CreatedDate  string `json:"createdDate" bson:"createdDate"`
	UserID       string `json:"user_id" bson:"user_id"`
	IsActive     bool   `json:"isActive" bson:"isActive"`
}

type NewTodo struct {
	Text   string `json:"text" bson:"text"`
	UserID string `json:"userId" bson:"userId"`
}

type Todo struct {
	ID   string `json:"id" bson:"id"`
	Text string `json:"text" bson:"text"`
	Done bool   `json:"done" bson:"done"`
	User *User  `json:"user" bson:"user"`
}

type User struct {
	ID   string `json:"id" bson:"id"`
	Name string `json:"name" bson:"name"`
}
